#include "aux.h"

void Help (void) { printf(
	M1 PROGNAME M0" reads a CSV file from standard input and filters it.\n"
	"Usage: "M1 PROGNAME M0" ["M1"MODE"M0"] ["M1"OPTIONS"M0"] ["M1"FIELDNAME ..."M0"]\n"
	"Modes:\n"
	M1"  -n    "M0"Non-fixed, named fields:\n"
	  "        "  "The program reads field names from the argument list ("M1"FIELDNAME"M0"S)\n"
	  "        "  "and compares them with the first line of the CSV file, then reads in\n"
	  "        "  "all lines and prints these fields.\n"
	  "        "  "Separate field names with a single \""M1"."M0"\".\n"
	  "        "  "The name order is irrelevant, as is case.\n"
	M1"  -f    "M0"Fixed names for field positions:\n"
	  "        "  "The program reads field names from the argument list ("M1"FIELDNAME"M0"S)\n"
	  "        "  "and applies them to all lines. Field positions which are to be ignored\n"
	  "        "  "may be marked with a single \""M1"@"M0"\".\n"
	  "        "  "The argument order represents the field order in the CSV input.\n"
	M1"  -p    "M0"The programm reads field names from the first line and prints all fields\n"
	  "        "  "with their names from the first line.\n"
	  "        "  "In this mode, "M1"FIELDNAME"M0" specifications are neither needed nor possible.\n"
	  "        "  "(This is the default mode.)\n"
	"\n"
	"Options:\n"
	M1"  -a    "M0"Only use separator which was found in first line.\n"
	M1"  -b    "M0"Allow linebreaks in fields.\n"
	"\n"
	M1"  -s N  "M0"Skips the first "M1"N"M0" input lines.\n"
	  "        "  "(Skipped lines are NOT counted for line numbers.)\n"
	M1"  -l N  "M0"Limit parsing to "M1"N"M0" input lines.\n"
	  "        "  "As soon as the "M1"N"M0"th line is reached (skipped lines not counted),\n"
	  "        "  "the program will terminate. Limiting to zero lines is of course useless,\n"
	  "        "  "except for mode "M1"-p"M0" (preset field names), where no content parsing\n"
	  "        "  "will be done, instead the program will terminate after printing\n"
	  "        "  "all field names as found on first line.\n"
	"\n"
	M1"  -e    "M0"Don't quit on parse errors.\n"
	M1"  -F    "M0"Flush stdout after every parsed input line.\n"
	M1"  -v    "M0"Verbose parsing on stderr.\n"
	"\n"
	M1"  -h    "M0"This help\n"
	M1"  -V    "M0"Program version\n"
	"\n"
); exit(0); }

void Version (void) { printf(
	PROGNAME " v" VERSION "\n"
	"Written by Maximilian Eul <mle@multinion.de>, June 2011.\n"
	"\n"
); exit(0); }
