#include "aux.h"
#include "const.h"
#include <stdio.h>

void Help (void) { printf(
	"Reads a CSV file from standard input and outputs a cleaner format.\n"
	"Usage: "M1 PROGNAME M0" ["M1"MODE"M0"] ["M1"OPTIONS"M0"] [--] ["Mu "COLUMNNAME"M0"...]\n"
	"Input modes:\n"
	" "M1"-n"M0", "M1"--named-columns"M0"  "
	"Non-fixed, named columns:\n"
	"            The program reads column names from the argument list\n"
	"            and compares them to the first line of the CSV input,\n"
	"            printing only the named columns.\n"
	"            Separate column names with a single \""M1 NAME_SEPARATOR M0"\" argument!\n"
	"            The name order is irrelevant, as is case.\n"
	" "M1"-g"M0", "M1"--assigned-names"M0"  "
	"Names assigned to column positions:\n"
	"            The program reads column names from the argument list and\n"
	"            applies them to all lines.  The special name \""M1 OMIT_COLUMN M0"\"\n"
	"            causes columns to be ignored.  The argument order represents\n"
	"            the column order in the CSV input.\n"
	" "M1"-a"M0", "M1"--auto-columns"M0"  "
	"Automatic column names:\n"
	"            Column names will be read automatically from the first CSV line.\n"
	"            In this mode, "Mu "COLUMNNAME"M0" specifications are\n"
	"            neither needed nor possible.\n"
	"            (This is the default mode.)\n"
	" "M1"-i"M0", "M1"--numbered-columns"M0"  "
	"Numbered columns:\n"
	"            In this mode, the columns will be automatically numbered,\n"
	"            starting from zero.  Similar to \""M1"-g 0 1 2 3"M0"...\",\n"
	"            but will force the "M1"-j"M0" output mode to print each line\n"
	"            as an array instead of an object.  Not compatible with "M1"-J"M0" mode.\n"
	"            Causes the "M1"-X"M0" mode not to output any header names.\n"
	"\n"
	"Options:\n"
	"  "M1"-m"M0", "M1"--simple"M0"  "
	"Output in simple format. (This is the default format.)\n"
	"  "M1"-j"M0", "M1"--json"M0"    "
	"Output in JSON format.\n"
	"  "M1"-J"M0", "M1"--compact-json"M0"  "
	                      "Output in compact JSON format\n"
	"                      (an object with 'columns' and 'lines' keys).\n"
	"  "M1"-X"M0", "M1"--shell-vars"M0"  "
	                      "Output in shell variable assignment format.\n"
	"  "M1"-d"M0", "M1"--separator"M0" "Mu "C"M0"  "
	                     "Use field separator character "Mu "C"M0".\n"
	"                     The special value \""M1"auto"M0"\" causes auto-detection\n"
	"                     on the first input line (this is the default mode).\n"
	"  "M1"-b"M0", "M1"--allow-breaks"M0"  "
	                      "Allow linebreaks within doublequoted fields.\n"
	"  "M1"-s"M0", "M1"--skip "M0 Mu "N"M0"  "
	                "Skip the first "Mu "N"M0" input lines.\n"
	"                In modes "M1"-n"M0" and "M1"-a"M0", skip the first N input lines\n"
	"                after the header line.\n"
	"                Setting "Mu "N"M0" to zero means no skip (this is the default).\n"
	"  "M1"-l"M0", "M1"--limit "M0 Mu "N"M0"  "
	                 "Stop after the "Mu "N"M0"th input line.\n"
	"                 In modes "M1"-n"M0" and "M1"-a"M0", the header line is not counted.\n"
	"                 Setting "Mu "N"M0" to zero removes the limit (this is the default).\n"
	"\n"
	"  "M1"-e"M0", "M1"--ignore-errors"M0"  "
	                       "Don't stop on encountering malformed CSV input.\n"
	"  "M1"-F"M0", "M1"--flush"M0"          "
	                       "Flush the output after every input line.\n"
	"  "M1"-M"M0", "M1"--keep-bom"M0"  "
	                  "Don't try to remove UTF-8/16 BOMs from the first line.\n"
	"  "M1"-v"M0", "M1"--verbose"M0"   "
	                  "Print parsing status output on stderr.\n"
	"  "M1"-h"M0", "M1"--help"M0"      "
	                  "This help\n"
	"  "M1"-V"M0", "M1"--version"M0"   "
	                  "Program version\n"
	"\n"
); }

void Version (void) { printf(
	PROGNAME " v" VERSION "\n"
	"Written by Maximilian Eul <maximilian@eul.cc>, " VERDATE ".\n"
	"\n"
); }

